-- Enable pgvector extension for vector operations
CREATE EXTENSION IF NOT EXISTS "vector" WITH SCHEMA "extensions";

-- Create album embeddings table
CREATE TABLE IF NOT EXISTS "public"."album_embeddings" (
  "id" bigint NOT NULL,
  "album_id" bigint NOT NULL,
  "title_embedding" vector(1536),
  "artist_embedding" vector(1536),
  "combined_embedding" vector(1536),
  "temporal_embedding" vector(1536),
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."album_embeddings" OWNER TO "postgres";

ALTER TABLE "public"."album_embeddings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME "public"."album_embeddings_id_seq"
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1
);

-- Create artist embeddings table
CREATE TABLE IF NOT EXISTS "public"."artist_embeddings" (
  "id" bigint NOT NULL,
  "artist_id" bigint NOT NULL,
  "name_embedding" vector(1536),
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."artist_embeddings" OWNER TO "postgres";

ALTER TABLE "public"."artist_embeddings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME "public"."artist_embeddings_id_seq"
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1
);

-- Create conversation embeddings table
CREATE TABLE IF NOT EXISTS "public"."conversation_embeddings" (
  "id" bigint NOT NULL,
  "user_id" uuid NOT NULL,
  "message_embedding" vector(1536),
  "response_embedding" vector(1536),
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."conversation_embeddings" OWNER TO "postgres";

ALTER TABLE "public"."conversation_embeddings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME "public"."conversation_embeddings_id_seq"
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1
);

-- Add primary key constraints
ALTER TABLE ONLY "public"."album_embeddings"
  ADD CONSTRAINT "album_embeddings_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."artist_embeddings"
  ADD CONSTRAINT "artist_embeddings_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."conversation_embeddings"
  ADD CONSTRAINT "conversation_embeddings_pkey" PRIMARY KEY ("id");

-- Add foreign key constraints
ALTER TABLE ONLY "public"."album_embeddings"
  ADD CONSTRAINT "album_embeddings_album_id_fkey" FOREIGN KEY ("album_id") REFERENCES "public"."album"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."artist_embeddings"
  ADD CONSTRAINT "artist_embeddings_artist_id_fkey" FOREIGN KEY ("artist_id") REFERENCES "public"."artist"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."conversation_embeddings"
  ADD CONSTRAINT "conversation_embeddings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

-- Create unique constraints to prevent duplicate embeddings
ALTER TABLE ONLY "public"."album_embeddings"
  ADD CONSTRAINT "album_embeddings_album_id_unique" UNIQUE ("album_id");

ALTER TABLE ONLY "public"."artist_embeddings"
  ADD CONSTRAINT "artist_embeddings_artist_id_unique" UNIQUE ("artist_id");

-- Create vector similarity search indexes
CREATE INDEX IF NOT EXISTS "album_embeddings_combined_embedding_idx" 
  ON "public"."album_embeddings" USING ivfflat ("combined_embedding" vector_cosine_ops);

CREATE INDEX IF NOT EXISTS "album_embeddings_temporal_embedding_idx" 
  ON "public"."album_embeddings" USING ivfflat ("temporal_embedding" vector_cosine_ops);

CREATE INDEX IF NOT EXISTS "album_embeddings_title_embedding_idx" 
  ON "public"."album_embeddings" USING ivfflat ("title_embedding" vector_cosine_ops);

CREATE INDEX IF NOT EXISTS "album_embeddings_artist_embedding_idx" 
  ON "public"."album_embeddings" USING ivfflat ("artist_embedding" vector_cosine_ops);

CREATE INDEX IF NOT EXISTS "artist_embeddings_name_embedding_idx" 
  ON "public"."artist_embeddings" USING ivfflat ("name_embedding" vector_cosine_ops);

-- Create regular indexes for performance
CREATE INDEX IF NOT EXISTS "album_embeddings_album_id_idx" ON "public"."album_embeddings" ("album_id");
CREATE INDEX IF NOT EXISTS "artist_embeddings_artist_id_idx" ON "public"."artist_embeddings" ("artist_id");
CREATE INDEX IF NOT EXISTS "conversation_embeddings_user_id_created_at_idx" ON "public"."conversation_embeddings" ("user_id", "created_at");

-- Function to perform vector similarity search
CREATE OR REPLACE FUNCTION match_albums_by_type(
  query_embedding vector(1536),
  embedding_column text,
  match_threshold float DEFAULT 0.7,
  match_count int DEFAULT 10
)
RETURNS TABLE (
  album_id bigint,
  title text,
  artist_name text,
  release_year bigint,
  purchase_date date,
  acquired_date date,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY EXECUTE format(
    'SELECT 
      ae.album_id,
      a.title,
      ar.name as artist_name,
      a.release_year,
      a.purchase_date,
      a.acquired_date,
      1 - (ae.%I <=> $1) as similarity
    FROM album_embeddings ae
    JOIN album a ON ae.album_id = a.id
    JOIN artist ar ON a.artist_id = ar.id
    WHERE 1 - (ae.%I <=> $1) > $2
    ORDER BY ae.%I <=> $1
    LIMIT $3',
    embedding_column, embedding_column, embedding_column
  ) USING query_embedding, match_threshold, match_count;
END;
$$;

-- Function to perform artist similarity search
CREATE OR REPLACE FUNCTION match_artists_by_name(
  query_embedding vector(1536),
  match_threshold float DEFAULT 0.7,
  match_count int DEFAULT 10
)
RETURNS TABLE (
  artist_id bigint,
  name text,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    ae.artist_id,
    ar.name,
    1 - (ae.name_embedding <=> query_embedding) as similarity
  FROM artist_embeddings ae
  JOIN artist ar ON ae.artist_id = ar.id
  WHERE 1 - (ae.name_embedding <=> query_embedding) > match_threshold
  ORDER BY ae.name_embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Enable RLS on embedding tables
ALTER TABLE "public"."album_embeddings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."artist_embeddings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."conversation_embeddings" ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for embedding tables
CREATE POLICY "Enable read access for all users" ON "public"."album_embeddings" FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON "public"."artist_embeddings" FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON "public"."conversation_embeddings" FOR SELECT USING (true);

CREATE POLICY "Enable insert access for users and service" ON "public"."album_embeddings" 
  FOR INSERT WITH CHECK ((auth.role() = 'authenticated'::text) OR (auth.role() = 'service_role'::text));

CREATE POLICY "Enable insert access for users and service" ON "public"."artist_embeddings" 
  FOR INSERT WITH CHECK ((auth.role() = 'authenticated'::text) OR (auth.role() = 'service_role'::text));

CREATE POLICY "Enable insert access for users and service" ON "public"."conversation_embeddings" 
  FOR INSERT WITH CHECK ((auth.role() = 'authenticated'::text) OR (auth.role() = 'service_role'::text));

CREATE POLICY "Enable update access for users and service" ON "public"."album_embeddings" 
  FOR UPDATE USING ((auth.role() = 'authenticated'::text) OR (auth.role() = 'service_role'::text));

CREATE POLICY "Enable update access for users and service" ON "public"."artist_embeddings" 
  FOR UPDATE USING ((auth.role() = 'authenticated'::text) OR (auth.role() = 'service_role'::text));

CREATE POLICY "Enable delete access for users and service" ON "public"."album_embeddings" 
  FOR DELETE USING ((auth.role() = 'authenticated'::text) OR (auth.role() = 'service_role'::text));

CREATE POLICY "Enable delete access for users and service" ON "public"."artist_embeddings" 
  FOR DELETE USING ((auth.role() = 'authenticated'::text) OR (auth.role() = 'service_role'::text));

CREATE POLICY "Enable delete access for users and service" ON "public"."conversation_embeddings" 
  FOR DELETE USING ((auth.role() = 'authenticated'::text) OR (auth.role() = 'service_role'::text));

-- Grant permissions
GRANT ALL ON TABLE "public"."album_embeddings" TO "anon";
GRANT ALL ON TABLE "public"."album_embeddings" TO "authenticated";
GRANT ALL ON TABLE "public"."album_embeddings" TO "service_role";

GRANT ALL ON SEQUENCE "public"."album_embeddings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."album_embeddings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."album_embeddings_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."artist_embeddings" TO "anon";
GRANT ALL ON TABLE "public"."artist_embeddings" TO "authenticated";
GRANT ALL ON TABLE "public"."artist_embeddings" TO "service_role";

GRANT ALL ON SEQUENCE "public"."artist_embeddings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."artist_embeddings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."artist_embeddings_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."conversation_embeddings" TO "anon";
GRANT ALL ON TABLE "public"."conversation_embeddings" TO "authenticated";
GRANT ALL ON TABLE "public"."conversation_embeddings" TO "service_role";

GRANT ALL ON SEQUENCE "public"."conversation_embeddings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."conversation_embeddings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."conversation_embeddings_id_seq" TO "service_role";

-- Grant execute permissions on functions
GRANT EXECUTE ON FUNCTION match_albums_by_type(vector(1536), text, float, int) TO "anon";
GRANT EXECUTE ON FUNCTION match_albums_by_type(vector(1536), text, float, int) TO "authenticated";
GRANT EXECUTE ON FUNCTION match_albums_by_type(vector(1536), text, float, int) TO "service_role";

GRANT EXECUTE ON FUNCTION match_artists_by_name(vector(1536), float, int) TO "anon";
GRANT EXECUTE ON FUNCTION match_artists_by_name(vector(1536), float, int) TO "authenticated";
GRANT EXECUTE ON FUNCTION match_artists_by_name(vector(1536), float, int) TO "service_role"; 